### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by ympavlov**
Fixed: build (for me: Ubuntu 18.04), ls -s output

### CODE REVIEW

**Comment by Overv** [comment]
You should update your version of FUSE to v3 rather than trying to link with the old version of the library.

**Comment by ympavlov** [comment]
I've changed fuse -> fuse3. Should work, but haven't tested since have no fuse3 with OpenCL on my systems

**Comment by Overv** [comment]
The `-l fuse3` is not necessary since pkg-config already adds that.

**Comment by ympavlov** [comment]
No, there's no backport for Ubuntu 18.04

Sorry, I didn't understand pkg-config role since I havn't pkg-config on my system. The -l fuse3 is really unnecessary

**Comment by ympavlov** [comment]
I'll create new request without Makefile change

**Pull request closed without merging**
